from launch import LaunchDescription
from launch.actions import DeclareLaunchArgument
from launch.substitutions import LaunchConfiguration
from launch_ros.actions import Node


def generate_launch_description() -> LaunchDescription:
    return LaunchDescription([
        DeclareLaunchArgument('port', default_value='/dev/ttyUSB0'),
        DeclareLaunchArgument('baud', default_value='115200'),
        DeclareLaunchArgument('command_topic', default_value='/mycobot/joint_commands'),
        DeclareLaunchArgument('state_topic', default_value='/mycobot/joint_states'),
        DeclareLaunchArgument('ee_pose_topic', default_value='/mycobot/ee_pose'),
        DeclareLaunchArgument('joint_state_source', default_value='command_echo'),
        DeclareLaunchArgument('gripper_command_topic', default_value='/mycobot/gripper/command'),
        DeclareLaunchArgument('gripper_value_topic', default_value='/mycobot/gripper/value'),
        DeclareLaunchArgument('gripper_calibration_topic', default_value='/mycobot/gripper/calibrate'),
        DeclareLaunchArgument('position_unit', default_value='rad'),
        DeclareLaunchArgument('command_speed', default_value='85'),
        DeclareLaunchArgument('fresh_mode', default_value='1'),
        DeclareLaunchArgument('gripper_speed', default_value='30'),
        DeclareLaunchArgument('command_rate_hz', default_value='30.0'),
        DeclareLaunchArgument('state_publish_rate_hz', default_value='10.0'),
        DeclareLaunchArgument('ee_pose_publish_rate_hz', default_value='5.0'),
        DeclareLaunchArgument('enable_ee_pose_publish', default_value='false'),
        DeclareLaunchArgument('send_only_on_change', default_value='true'),
        DeclareLaunchArgument('change_threshold_deg', default_value='0.8'),
        DeclareLaunchArgument('profile_io_timing', default_value='false'),
        DeclareLaunchArgument('io_timing_log_every_n', default_value='120'),
        DeclareLaunchArgument('io_timing_outlier_ms', default_value='20.0'),
        DeclareLaunchArgument('clear_queue_on_send_outlier_ms', default_value='400.0'),
        DeclareLaunchArgument('clear_queue_cooldown_sec', default_value='1.0'),
        Node(
            package='mycobot_jointstate_controller',
            executable='jointstate_controller_node',
            name='mycobot_jointstate_controller',
            output='screen',
            parameters=[{
                'port': LaunchConfiguration('port'),
                'baud': LaunchConfiguration('baud'),
                'command_topic': LaunchConfiguration('command_topic'),
                'state_topic': LaunchConfiguration('state_topic'),
                'ee_pose_topic': LaunchConfiguration('ee_pose_topic'),
                'joint_state_source': LaunchConfiguration('joint_state_source'),
                'gripper_command_topic': LaunchConfiguration('gripper_command_topic'),
                'gripper_value_topic': LaunchConfiguration('gripper_value_topic'),
                'gripper_calibration_topic': LaunchConfiguration('gripper_calibration_topic'),
                'position_unit': LaunchConfiguration('position_unit'),
                'command_speed': LaunchConfiguration('command_speed'),
                'fresh_mode': LaunchConfiguration('fresh_mode'),
                'gripper_speed': LaunchConfiguration('gripper_speed'),
                'command_rate_hz': LaunchConfiguration('command_rate_hz'),
                'state_publish_rate_hz': LaunchConfiguration('state_publish_rate_hz'),
                'ee_pose_publish_rate_hz': LaunchConfiguration('ee_pose_publish_rate_hz'),
                'enable_ee_pose_publish': LaunchConfiguration('enable_ee_pose_publish'),
                'send_only_on_change': LaunchConfiguration('send_only_on_change'),
                'change_threshold_deg': LaunchConfiguration('change_threshold_deg'),
                'profile_io_timing': LaunchConfiguration('profile_io_timing'),
                'io_timing_log_every_n': LaunchConfiguration('io_timing_log_every_n'),
                'io_timing_outlier_ms': LaunchConfiguration('io_timing_outlier_ms'),
                'clear_queue_on_send_outlier_ms': LaunchConfiguration('clear_queue_on_send_outlier_ms'),
                'clear_queue_cooldown_sec': LaunchConfiguration('clear_queue_cooldown_sec'),
            }],
        ),
    ])
